print ("===============welcome to my project===============")
print("Welcome to the interactive Personal Data Collecter!")
print("")
print("Project: Fundamental Booster")

print ("")
name= input ("enter the name :")
print("")
age= int(input("enter the age :"))
print("")
height =float(input("enter the height:"))
print("")
number =int(input("enter the number"))
print("")
print("Thank you! Here is the information we")
print("")
print(f"name:{name}(type:{type (name)},memory address:{id (name)})")
print("")
print(f"age:{age}(type:{type (age)},memory address:{id (age)})")
print("")
print(f"height:{height}(type:{type (height)},memory address:{id (height)})")
print("")
print(f"number:{number}(type:{type (number)},memory address:{id (number)})")
print("")
print(f"Your birth year is approximately: {2026-age} (based on your age of {age})")
print("")

print("Thank you for using the Personal Data Collector, Goodbye")
